#!/bin/bash

set -o errexit  # exit on error
set -o pipefail # trap pipe fails
set -o nounset  # trap unset vars
# set -o xtrace
################################################################################

# Quick instructions
#
# 1. Ensure emacs source is in `$LOCAL_EMACS` (`/tmp/emacs`). Possibly, this
#    might be done using `cp -a /gits/emacs /tmp`
#
# 2. run `./compile`
#
# This will leave emacs files in `$TEMP_FILES_DIR` (`/tmp/emacs-files`) with
# their final location expected to be `$INSTALL_DIR` (`/opt/emacs-VERSION_DATE`)
#
# 3. `cp -a /tmp/emacs-files /`
#
# 4. `cd /opt && ln -s emacs-VERSION_DATE emacs`

EMACS_REPO="git://git.savannah.gnu.org/emacs.git"
LOCAL_EMACS="/tmp/emacs"
EMACS_GIT="$HOME/gits/emacs"
INSTALL_DIR="/opt/emacs"
TEMP_FILES_DIR="/tmp/emacs-files"
TEMP_INSTALL_DIR="$TEMP_FILES_DIR$INSTALL_DIR"

if [[ ! -d "$LOCAL_EMACS" ]] ; then
    echo "\"$LOCAL_EMACS\" doesn't exist"
    exit 1
fi

if [[ -d "$TEMP_INSTALL_DIR" ]] ; then
    rm -rf "$TEMP_INSTALL_DIR"
fi

mkdir -p "$TEMP_INSTALL_DIR"

# if false ; then
#     git clone "$EMACS_REPO" --depth=1 "$LOCAL_EMACS"
# else
#     [[ -e "$LOCAL_EMACS" ]] && rm -rf "$LOCAL_EMACS"
#     mkdir -p "$LOCAL_EMACS"
#     cp -a "$EMACS_GIT/" "$LOCAL_EMACS/.."
# fi

cd "$LOCAL_EMACS"

./autogen.sh

configure_opts=
configure_opts+=" --prefix=$INSTALL_DIR"

configure_opts+=" --with-cairo"
configure_opts+=" --with-libsystemd"
configure_opts+=" --with-mailutils"
configure_opts+=" --with-native-compilation"
configure_opts+=" --with-pop=yes"
configure_opts+=" --with-sound=alsa"
configure_opts+=" --with-toolkit-scroll-bars"
configure_opts+=" --with-x-toolkit=gtk3"
configure_opts+=" --with-x=yes"
configure_opts+=" --without-gconf"

./configure $configure_opts CFLAGS="-g -O2"

NPROC=$(nproc) || NPROC=2
make -j$NPROC && make install prefix=$TEMP_INSTALL_DIR -j$NPROC

EMACS_VERSION=$(grep PACKAGE_VERSION "$LOCAL_EMACS/src/config.h" | \
                sed -e 's/[^"]*"//' -e 's/"//')
YYYYMMDD=$(date +%Y%m%d)
mv $TEMP_INSTALL_DIR "$TEMP_INSTALL_DIR-${EMACS_VERSION}_$YYYYMMDD"

printf "\n\n\n"
echo "your files are in $TEMP_FILES_DIR,"
echo "ready to be copied into $INSTALL_DIR"
echo "with \`cp -a $TEMP_FILES_DIR/* /\`"
